src/Entity/Users.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UsersRepository")
 */
class Users implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $additional_address;

    /**
     * @ORM\Column(type="integer")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone_number;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $resetToken;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    public function getRoles(): ?array
    {
        return $this->roles;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getAdditionalAddress(): ?string
    {
        return $this->additional_address;
    }

    public function setAdditionalAddress(string $additional_address): self
    {
        $this->additional_address = $additional_address;

        return $this;
    }

    public function getPostalCode(): ?int
    {
        return $this->postal_code;
    }

    public function setPostalCode(int $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(?string $resetToken): self
    {
        $this->resetToken = $resetToken;

        return $this;
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta
        name="description" content="South-West-Store est la source la plus fiable pour acheter les sneakers les plus rares et les plus convoitées au monde. Vous trouverez un large choix avec un arrivage régulier.">
        <!-- FavIcone -->
        <link rel="icon" type="image/png" href="/img/South-West-Store-Logo.png">
        <title>
            {% block title %}{% endblock %}
        </title>
        <!-- Bootstrap-->
        <link
        rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <!-- Fontawesome-->
        <link
        rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
        <!-- Google font-->
        <link
        href="https://fonts.googleapis.com/css?family=Emilys+Candy|Josefin+Sans|Shadows+Into+Light|Caveat|Love+Ya+Like+A+Sister|Rock+Salt&display=swap" rel="stylesheet">
        <!--Alert Style-->
        <link
        rel="stylesheet" href="sweetalert2.min.css">
        <!-- My styles -->
        <link rel="stylesheet" href="/css/styles.css"> {% block stylesheets %}{% endblock %}
        </head>

        <body>

            <header>
                <!-- <div class="vid">
                    <video width="100%" autoplay="autoplay" muted="muted" loop="loop">
                        <source src="/img/home/shoes.mp4" type="video/mp4">
                    </video>
                </div> -->
                <div class="container h-100">
                    <div class="d-flex h-100 text-center justify-content-around align-items-center">

                        <div class="col-md-2 col-sm-12">
                            <a class="nav-link" href="{{ path ('homepage') }}"><img src="/img/South-West-Store-Logo.png" alt="Logo South-West-Store"></a>
                        </div>
                        <div class=" col-md-8 align-self-center d-none d-md-inline-block">
                            <h1>Bienvenue dans la boutique de Nemo</h1>
                        </div>
                    </div>
                </div>
            </header>


            <nav id="navbar" class="navbar">
                <div class="left">

                    <a class="nav-link" href="{{ path ('show_products') }}">Boutique</a>

                    {% if not is_granted('IS_AUTHENTICATED_REMEMBERED') %}
                        <a class="nav-link" href="{{ path('app_register') }}">S'inscrire</a>

                        <a class="nav-link" href="{{ path('app_login') }}">Connexion</a>

                    {% else %}

                        {% if is_granted(expression('"ROLE_ADMIN" in roles or (not is_anonymous() and not "ROLE_USER" in roles)')) %}
                            <div class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admin</a>

                                <div class="dropdown-menu">
                                    <a class="dropdown-item nav-link" href="{{ path('add_product') }}">Ajouter</a>

                                    <a class="dropdown-item nav-link" href="{{ path('modify_product') }}">Modifier</a>

                                    <a class="dropdown-item nav-link" href="{{ path('admin_orders') }}">Commandes</a>

                                </div>
                            </div>

                        {% else %}
                            <div class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{ app.user.firstName }}</a>

                                <div class="dropdown-menu">
                                    <a class="dropdown-item nav-link" href="{{ path('user_session') }}">Profil</a>

                                    <a class="dropdown-item nav-link" href="{{ path('user_orders') }}">Commandes</a>
                                </div>
                            </div>

                        {% endif %}
                    {% endif %}
                </div>
                <div class="right">
                    {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}

                        <a class="nav-link" href="{{ path('app_logout') }}">Déconnexion</a>

                    {% endif %}


                    <a class="nav-link" href="{{path('cart_details')}}">Panier ({{app.session.get('cart')|length}})</a>

                </div>


            </nav>

            {% block body %}{% endblock %}
            <div class="bg-light row text-center" id="inf_foot">
                <div class="col-md-3 inf">
                    <p>
                        <i class="fas fa-truck"></i>
                    </p>
                    <h5>Livraison Gratuite</h5>
                    <p>Livraison gratuite en France</p>
                    <p class="info-foot">Métropolitaine</p>
                </div>
                <div class="col-md-3 inf">
                    <p>
                        <i class="fas fa-lock"></i>
                    </p>
                    <h5>Paiement Sécurisé</h5>
                    <p>Paiement 100% sécurisé</p>
                    <p class="info-foot">Visa, Mastercard, Paypal</p>
                </div>
                <div class="col-md-3 inf">
                    <p>
                        <i class="far fa-comments"></i>
                    </p>
                    <h5>Service Client</h5>
                    <p>Une question ? Besoin d'un conseil ?</p>
                    <p class="info-foot">01 84 60 90 20</p>
                </div>
                <div class="col-md-3 inf">
                    <p>
                        <i class="fas fa-exchange-alt"></i>
                    </p>
                    <h5>Retour</h5>
                    <p>À compter de la réception de la commande, vous</p>
                    <p class="info-foot">bénéficiez de 15 jours pour changer d'avis</p>
                </div>
            </div>
            <footer>
                <p class="text-center">&copy; Copyright 2019 - La boutique de Nemo - Ne pas reproduire |
                    <a href="{{ path('mentions') }}">Mentions légales</a>
                    |
                    <a href="{{ path('cgv') }}">CGV</a>
                    |
                    <a href="{{ path('contact') }}">Nous contacter</a>
                    |
                    <a href="{{ path('a_propos') }}">A propos</a>

                </p>

            </footer>
            <!-- Jquery -->
            <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
            <!-- Bootstrap-->
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
            <!--Script alert buttons-->
            <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
            <!-- Mon script-->
            <script src="/js/script.js"></script>


            {% block javascripts %}{% endblock %}

        </body>
    </html>